#ifndef __MAGICNUMBERS_H__
#define __MAGICNUMBERS_H__

#define NICK_MAX_LENGTH 9
#define AWAY_MAX_LENGTH 200
#define TOPIC_MAX_LENGTH 200
#define CHANNEL_NAME_MAX_LENGTH 32
#define KICKMSG_MAX_LENGTH 200
#define CLIENT_MAX_CHANNELS 10
#define SERVER_MAX_CLIENTS 20
#define CHANNEL_KEY_MAX_LENGTH 16
#define DEFAULT_MAX_CHAN_CLIENTS 42

#endif